Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/LineLength:
  Max: 90

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Max: 200
